caconfig:
    carootpath: certs
headermap:
    headers: {}
    setcookie: []
mitmproxy:
    addrport: :9080
    sslinsecure: true
    includedomain: []
    excludedomain:
        - github.com
        - github.io
        - github.com.cn
        - github.io.cn
        - baidu.com
    filtersuffix:
        - .png
        - .jpg
redis:
    address: 127.0.0.1:6379
