caconfig:
    carootpath: certs
headermap:
    headers: {}
    setcookie: []
mitmproxy:
    addrport: ""
    sslinsecure: false
    includedomain: []
    excludedomain:
        - bilibili.com
        - github.com
        - baidu.com
        - wetab.link
        - avatars.githubusercontent.com
        - cn.bing.com
        - api.wetab.link
        - luna-ai.youdao.com
        - www.bilibili.com
        - youdao.com
        - microsoft.com
        - gator.volces.com
        - api-static.aippt.cn
    filtersuffix:
        - .js
redis:
    address: 127.0.0.1:6379
templatefilters:
    severity: high
    excludeseverities: critical,medium,low,info
    protocoltypes: http
    excludeprotocoltypes: ""
    authors: []
    tags:
        - rails
    excludetags: []
    includetags: []
    ids: []
    excludeids: []
    templatecondition: []
    enablecheck: false
