caconfig:
    carootpath: certs
headermap:
    headers: {}
    setcookie: []
mitmproxy:
    addrport: ""
    sslinsecure: false
    includedomain:
        - 124.70.64.48:48519
    excludedomain:
        - github.com
        - baidu.com
        - wetab.link
        - avatars.githubusercontent.com
        - cn.bing.com
        - api.wetab.link
        - luna-ai.youdao.com
        - www.bilibili.com
        - chaos.com
        - youdao.com
        - microsoft.com
    filtersuffix: []
redis:
    address: 127.0.0.1:6379
