caconfig:
    carootpath: ""
headermap:
    setcookie: []
mitmproxy:
    addr_port: "7777"
    addrport: :7777
    excludedomain:
        - bilibili.com
        - github.com
        - baidu.com
        - wetab.link
        - avatars.githubusercontent.com
        - cn.bing.com
        - api.wetab.link
        - luna-ai.youdao.com
        - www.bilibili.com
        - youdao.com
        - microsoft.com
        - gator.volces.com
        - api-static.aippt.cn
        - services.addons.mozilla.org
        - mozilla.org
        - mozilla.net
        - mozilla.com
        - firefox.com
        - firefox.cn
        - firefox.net
        - firefox.org
        - firefox.com.cn
    filtersuffix:
        - .aac
        - .abw
        - .aif
        - .aifc
        - .aiff
        - .apk
        - .arc
        - .au
        - .avi
        - .azw
        - .bat
        - .bin
        - .bmp
        - .bz
        - .bz2
        - .cmd
        - .cmx
        - .cod
        - .com
        - .csh
        - .css
        - .csv
        - .dll
        - .doc
        - .docx
        - .ear
        - .eot
        - .epub
        - .exe
        - .flac
        - .flv
        - .gif
        - .gz
        - .ico
        - .ics
        - .ief
        - .jar
        - .jfif
        - .jpe
        - .jpeg
        - .jpg
        - .less
        - .m3u
        - .mid
        - .midi
        - .mjs
        - .mkv
        - .mov
        - .mp2
        - .mp3
        - .mp4
        - .mpa
        - .mpe
        - .mpeg
        - .mpg
        - .pkg
        - .mpkg
        - .mpp
        - .mpv2
        - .odp
        - .ods
        - .odt
        - .oga
        - .ogg
        - .ogv
        - .ogx
        - .otf
        - .pbm
        - .pdf
        - .pgm
        - .png
        - .pnm
        - .ppm
        - .ppt
        - .pptx
        - .ra
        - .ram
        - .rar
        - .ras
        - .rgb
        - .rmi
        - .rtf
        - .scss
        - .sh
        - .snd
        - .svg
        - .swf
        - .tar
        - .tif
        - .tiff
        - .ttf
        - .vsd
        - .war
        - .wav
        - .weba
        - .webm
        - .webp
        - .wmv
        - .woff
        - .woff2
        - .xbm
        - .xls
        - .xlsx
        - .xpm
        - .xul
    includedomain: []
    ssl_insecure: false
    sslinsecure: true
redis:
    address: 127.0.0.1:6379
scanrate:
    globalrate: 50
    globalrateunit: second
    headlesshostconcurrency: 50
    headlesstemplateconcurrency: 30
    hostconcurrency: 100
    javascripttemplateconcurrency: 50
    probeconcurrency: 50
    templateconcurrency: 100
    templatepayloadconcurrency: 25
templatefilters:
    severity: critical,high,medium,low,info
    excludeseverities: ""
    protocoltypes: ""
    excludeprotocoltypes: ""
    authors: []
    tags:
        - webmin
    excludetags: []
    includetags: []
    ids: []
    excludeids: []
    templatecondition: []
    enablecheck: false
